
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import { ThemeProvider } from "./(Modules)/_Theme";
import Header from "./_Components/Shared/Header";
import Footer from "./_Components/Shared/Footer";
import ReactQueryProviders from "./_Providers/ReactQueryProvider";
import ToasterProvider from "./_Providers/ToastProvider";
import { EditArticleProviders } from "./_Providers/EditArticleProvider";
import EditCommentDialogContextProvider from "./(Modules)/_Comments/Context/EditCommentDialogContext";



const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Wiki app ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} antialiased`}>
        {" "}
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ReactQueryProviders>
            <ToasterProvider />
            <Header />
            <EditCommentDialogContextProvider>
              <EditArticleProviders>{children}</EditArticleProviders>
            </EditCommentDialogContextProvider>
            <Footer />
          </ReactQueryProviders>
        </ThemeProvider>
      </body>
    </html>
  );
}

